### ISSUE TITLE
Another key than F12

### ISSUE THREAD

**Issue by xmedeko** [SLaks/Ref12#14]
I would like to keep F12 it's original function and show the source by context menu only. Bacause it takes some time to load external source and it's not always reliable. (E.g. System.Delegate opens Roslyn source http://source.roslyn.codeplex.com/mscorlib/R/#0dd8585ba1833ad7.html but it's empty page)

**Comment by SLaks** [comment]
You can bind F12 to GoToDefinitionNative in Keyboard options.

**Comment by xmedeko** [comment]
Yep, thanks. But is it necessary to change the native function and then create a new one `GoToDefinitionNative`? IMHO it would be better to create a function `GoToDefinitionSource` and let the native function as is.

**Comment by SLaks** [comment]
Ref12 is designed to be strictly better than the built-in F12, so, yes, I think so.
The only situation I've found to prefer native F12 is if you want to quickly see a signature; for that, Alt+F12 (Peek Definition) is better anyway.
