### ISSUE TITLE
Need to enable NuGet package restore in the Ref12 solution

### ISSUE THREAD

**Issue by KirillOsenkov** [SLaks/Ref12#17]
Right now when I git clone and try to MSBuild, it fails because NuGets are missing. You should enable automatic package restore so that MSBuild would pull NuGets on build.

**Comment by SLaks** [comment]
I thought the new hotness was automatic package restore?
Or is that VS-only?

**Comment by sharwell** [comment]
@KirillOsenkov Building from the command line requires an explicit call to `nuget restore`. Building in the IDE automatically restores packages. This is by-design; see [Automatic Package Restore within Visual Studio](https://docs.nuget.org/consume/package-restore) and [Migrating to Automatic Package Restore](https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore).

**Comment by SLaks** [comment]
Yes; that's exactly what I mean.

**Comment by KrzysFR** [comment]
I've had the same issue for one of my repo, and I'm interested to know what is the current best practice on how to setup a git repository that anyone could build from the commandline and have the nuget packages restored, but without having to store NuGet.exe or packages/* in the repository itself (a couple of MB right now). 

I've used batch files that run a powershell script that tries to download NuGet.exe from nuget.org if it does not exists locally, but it does seems a bit be clunky. Is there a simplersolution where the build script could locate and use the NuGet.exe that is shipped with VS2015?

**Comment by sharwell** [comment]
@KrzysFR No one builds from the command line. And when they do, it doesn't matter whether they invoke msbuild directly or a build script.

I use this block for restoring NuGet.exe:

```powershell
# build the solution
$SolutionPath = "..\SolutionName.sln"

# make sure the script was run from the expected path
if (!(Test-Path $SolutionPath)) {
	$host.ui.WriteErrorLine('The script was run from an invalid working directory.')
	exit 1
}

$nuget = '..\.nuget\NuGet.exe'
If (-not (Test-Path $nuget)) {
	If (-not (Test-Path '..\.nuget')) {
		mkdir '..\.nuget'
	}

	$nugetSource = 'http://nuget.org/nuget.exe'
	Invoke-WebRequest $nugetSource -OutFile $nuget
}

&$nuget 'restore' $SolutionPath
```

**Comment by KrzysFR** [comment]
Well, I do sometimes build from the command line :)

This script looks fine, I'll probably adapt it to my needs. Thanks!

**Comment by KirillOsenkov** [comment]
I see, I didn't know that they'd obsoleted the MSBuild way. Sam, I do build from command line, FWIW :) In my opinion builds should be as self-contained as possible and GitClone+MSBuildSln should be all I need to produce a build of a project on any machine. Also builds in the IDE shouldn't differ from command line builds (again in my opinion). That's why I've filed the bug - I've done git clone followed by MSBuild Ref12.sln and it failed with an obscure message, this wasn't the best experience. I didn't know the new setup was intentional.

However of course none of this matters here :)
