### ISSUE TITLE
F12 for css

### ISSUE THREAD

**Issue by M-Zuber** [SLaks/Ref12#19]
Is there anyway to have this and be able to use `F12` to jump from `css` class use in `html` file to it's declaration?
ex:
```html
<div class="foo"></div>
```
I should still be able to jump to the file that defines `.foo`

**Comment by SLaks** [comment]
Web Essentials does that.  https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/HTML/Commands/GoToDefinitionCommandTarget.cs

**Comment by M-Zuber** [comment]
I have Web Essentials 2025. I'll have to check the settings when I am back by my machine, but to double check - WE and Ref12 should play nicely side by side?

**Comment by SLaks** [comment]
Yes; that should work fine.

WE2015 has the same feature; https://github.com/madskristensen/WebEssentials2015/blob/master/EditorExtensions/HTML/Commands/GoToDefinitionCommandTarget.cs
