### ISSUE TITLE
Error in VS2015 RTM

### ISSUE THREAD

**Issue by asherber** [SLaks/Ref12#20]
When I install this in VS2015 and hit F12, I get:

Method not found: 'Microsoft.CodeAnalysis.Document Microsoft.CodeAnalysis.Text.Extensions.GetOpenDocumentInCurrentContextWithChanges(Microsoft.VisualStudio.Text.ITextSnapshot)'.

**Comment by asherber** [comment]
Update: This is happening on only one of my two similarly configured machines.

**Comment by SLaks** [comment]
That method [exists](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.cs,82bf34180667ee95) in the current Roslyn sources; I'm not sure what could cause this.

Can you attach a debugger to the filing VS instance and check what versions of `Microsoft.CodeAnalysis.EditorFeatures.Text` are loaded?
I wonder if you have some other extension that is loading an older Roslyn build.

**Comment by asherber** [comment]
|Procexp shows ||Microsoft.CodeAnalysis.EditorFeatures.Text|.ni.dll, 
version 1.00.0.50618, dated 6/18/15, in a subfolder of 
C:\WINDOWS\assembly\NativeImages_v4.0.30319_32

I also see a Microsoft.CodeAnalysis.dll loaded, version 0.6.40331.3, and 
gacutil shows a number of Microsoft.CodeAnalysis.* assemblies there with 
a similar version number. I installed a preview build of Roslyn on this 
computer a year or two ago; maybe that's what's going on. If I can 
figure out how to uninstall it, I'll see if that fixes things.

**Comment by asherber** [comment]
Uninstalling the Roslyn preview didn't touch the files in the GAC, but I uninstalled them manually with gacutil, and now F12 works again. Interestingly, my other machine, on which F12 has been working all along, also had the Roslyn preview installed but didn't have the assemblies in the GAC. Thanks for your help.
