### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [SLaks/Ref12#27]

**Comment by HppZ** [comment]
it does not work in UWP app, right？

**Comment by xperiandri** [comment]
I was about updating extension manifest and check if it does not cause any issues in VS15
Looks like it works fine

**Comment by HppZ** [comment]
:), yeah, it works, but I want to step into .Net code when I debug my code, so : 
Do you know how to step into .Net source code in UWP / WPF / Console applications?
[Question on SO](http://stackoverflow.com/questions/37302859/how-to-debugging-net-source-code-with-vs2015-update1-in-uwp-wpf-console-app?noredirect=1#comment62129708_37302859)
