### ISSUE TITLE
Not working Core 1.0 or VS 2015

### ISSUE THREAD

**Issue by KriKan** [SLaks/Ref12#29]
I'm using VS2015 and created a Core 1.0 web application, I installed this from MSDN [https://visualstudiogallery.msdn.microsoft.com/f89b27c5-7d7b-4059-adde-7ccc709fa86e](url)
site. Still after pressing F12 I can see only the skeleton of implementation. Does this package doesn't work for latest versions of framework ?

**Comment by SLaks** [comment]
AFAIK, there is no hosted source for .Net Core, so there's nothing I can do.
